import React from 'react';
import { Zap, Lightbulb, TrendingDown, ArrowUpRight, CheckCircle2, AlertCircle } from 'lucide-react';

export default function InsightsPage() {
  const recommendations = [
    {
      title: 'Optimize Subscription Leakage',
      desc: "Our models detected 3 streaming services with no usage in 60 days. Cancelling could save $42.50/mo.",
      impact: 'High',
      type: 'leakage',
      icon: Zap,
      color: 'text-rose-400',
      bg: 'bg-rose-400/10'
    },
    {
      title: 'Dining Efficiency',
      desc: "You spend 40% more on Dining than the average user in your income bracket. Try meal prepping 2 more days/week.",
      impact: 'Medium',
      type: 'saving',
      icon: Lightbulb,
      color: 'text-amber-400',
      bg: 'bg-amber-400/10'
    },
    {
      title: 'Emergency Fund Boost',
      desc: "By rounding up your transactions to the nearest dollar, you could reach your milestone 3 months earlier.",
      impact: 'Medium',
      type: 'goal',
      icon: TrendingDown,
      color: 'text-indigo-400',
      bg: 'bg-indigo-400/10'
    }
  ];

  return (
    <div className="max-w-4xl mx-auto space-y-8 animate-in fade-in duration-700">
      <div>
        <h1 className="text-2xl md:text-3xl font-bold text-white mb-2">AI-Driven Insights</h1>
        <p className="text-slate-400">Personalized recommendations generated by your spending behavior models.</p>
      </div>

      <div className="grid grid-cols-1 gap-6">
        {recommendations.map((item, i) => (
          <div key={i} className="glass-panel p-8 flex flex-col md:flex-row gap-8 hover:bg-white/5 transition-colors cursor-default">
            <div className={`w-16 h-16 rounded-2xl ${item.bg} flex items-center justify-center ${item.color} shrink-0`}>
              <item.icon className="w-8 h-8" />
            </div>
            
            <div className="flex-1 space-y-4">
              <div className="flex items-center justify-between">
                 <h3 className="text-xl font-bold text-white">{item.title}</h3>
                 <span className={`px-2 py-1 rounded text-[10px] font-black uppercase tracking-widest ${
                   item.impact === 'High' ? 'bg-rose-500/20 text-rose-400' : 'bg-amber-500/20 text-amber-400'
                 }`}>
                   {item.impact} Impact
                 </span>
              </div>
              
              <p className="text-slate-400 leading-relaxed">
                {item.desc}
              </p>

              <div className="flex items-center gap-6 pt-2">
                 <button className="text-sm font-bold text-indigo-400 flex items-center gap-1 hover:text-white transition-colors">
                    Analyze More <ArrowUpRight className="w-4 h-4" />
                 </button>
                 <button className="text-sm font-bold text-slate-500 flex items-center gap-1 hover:text-white transition-colors">
                    Dismiss
                 </button>
              </div>
            </div>
          </div>
        ))}
      </div>

      <div className="glass-panel p-8 bg-indigo-600/5 text-center">
         <div className="w-12 h-12 bg-indigo-500/10 rounded-full flex items-center justify-center text-indigo-400 mx-auto mb-4">
            <CheckCircle2 className="w-6 h-6" />
         </div>
         <h4 className="text-lg font-bold mb-2">You're doing great!</h4>
         <p className="text-sm text-slate-500 max-w-sm mx-auto">
            Overall financial efficiency is up 12% compared to last month. Keep following your AI tips.
         </p>
      </div>
    </div>
  );
}
